import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";
import { ToastContainer } from 'react-toastify';
import StoreProvider from "@/components/StoreProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ToastContainer position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          <div className="grid grid-cols-5">
            <SideMenu />
            <div className="col-span-4">
              <Header />
              <div className="container mx-auto px-4 py-6">
                {children}
              </div>
            </div>

          </div>
        </body>
      </StoreProvider>

    </html>
  );
}
